id: opecha:P008219
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25800
  title: མཚོ་སྔོན་སི་ཁྲོན་ཀན་སུའུ་ཡུན་ནན་ཞིང་ཆེན་བཞིའི་བོད་ཁུལ་གྱི་གྲོང་སྡེའི་མིང་རྒྱ་བོད་ཤན་སྦྱར།
  volume: ''
  author: ''
