id: IC0AC4FAC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:04:05+00:00'
last_modified: '2022-06-08T08:00:59.659011+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25800
  title: མཚོ་སྔོན་སི་ཁྲོན་ཀན་སུའུ་ཡུན་ནན་ཞིང་ཆེན་བཞིའི་བོད་ཁུལ་གྱི་གྲོང་སྡེའི་མིང་རྒྱ་བོད་ཤན་སྦྱར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    099C:
      image_group_id: I1KG25802
      title: ''
      total_pages: 869
      order: 1
      base_file: 099C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
